# path: config/config.yaml

agent:
  conversational_chat: False
  # conversational_chat: true
  # Note: recommend GPT-4 to use conversational_chat mode

database:
  default_database: ethereum
  default_schema: core

model:
  llm_name: gpt-3.5-turbo
  # llm_name: gpt-4

tool:
  query_database_tool_top_k: 10
  query_database_tool_mode: flipside
  query_database_tool_return_direct_if_successful: False 
  check_table_summary_tool_mode: local
  check_table_metadata_tool_mode: local
  # DO NOT enable the following option unless you know what you are doing 
  query_database_tool_return_direct: False  
  # This option makes the tool return immediately even if the query is not successful
  # therefore, the tool will not perform correction and retry! 
  # use the query_database_tool_return_direct_if_successful option instead!

flipside:
  query_timeout: 5
  query_max_retries: 1
# agent_chain:
#  agent_executor_return_intermedidate_steps: False

metadata:
  context_ethereum_core_file: data/metadata/context_ethereum_core.json
  annotation_ethereum_core_file: data/metadata/annotation_ethereum_core_v1.json

ethereum_core_table_long_name:
  enabled_list:
    - "ethereum.core.ez_dex_swaps"
    - "ethereum.core.ez_current_balances"
    - "ethereum.core.ez_token_transfers"
    - "ethereum.core.dim_labels"
  full_list:
    - "ethereum.core.dim_contract_abis"
    - "ethereum.core.dim_contracts"
    - "ethereum.core.dim_contracts_extended"
    - "ethereum.core.dim_dates"
    - "ethereum.core.dim_dex_liquidity_pools"
    - "ethereum.core.dim_event_signatures"
    - "ethereum.core.dim_function_signatures"
    - "ethereum.core.dim_labels"
    - "ethereum.core.dim_nft_metadata"
    - "ethereum.core.ez_balance_deltas"
    - "ethereum.core.ez_current_balances"
    - "ethereum.core.ez_decoded_event_logs"
    - "ethereum.core.ez_dex_swaps"
    - "ethereum.core.ez_eth_transfers"
    - "ethereum.core.ez_nft_mints"
    - "ethereum.core.ez_nft_sales"
    - "ethereum.core.ez_nft_transfers"
    - "ethereum.core.ez_snapshot"
    - "ethereum.core.ez_token_transfers"
    - "ethereum.core.fact_blocks"
    - "ethereum.core.fact_contract_reads"
    - "ethereum.core.fact_decoded_event_logs"
    - "ethereum.core.fact_dex_pool_daily_reads"
    - "ethereum.core.fact_dex_pool_weekly_reads"
    - "ethereum.core.fact_eth_balances"
    - "ethereum.core.fact_hourly_token_prices"
    - "ethereum.core.fact_token_balances"
    - "ethereum.core.fact_token_transfers"
    - "ethereum.core.fact_traces"
    - "ethereum.core.fact_transactions"

logging:
  default:
    log_level: INFO
    log_to_console: True
    log_to_file: True
    log_format: "%(asctime)s [%(name)s] [%(levelname)s] [%(module)s:%(lineno)d] [%(funcName)s]: %(message)s"
    date_format: "%Y-%m-%d %H:%M:%S"
    log_file_path: "logs/chatweb3.log"

  development:
    log_level: DEBUG
    log_to_console: True
    log_to_file: True

  production:
    log_level: WARNING
    log_to_console: False
    log_to_file: True